language: node_js
sudo: true
dist: trusty

node_js:
  - '6.9.4'

scripts: {
  "test": "ng test --single-run"
},

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start